[package]
name = "clerk-rs"
version = "0.1.2"
authors = ["DarrenBaldwin07"]
description = "An unofficial Rust SDK for the Clerk API"
repository = "https://github.com/Cincinnati-Ventures/clerk-rs"
homepage = "https://cincinnati.ventures"
keywords = ["clerk", "auth", "sdk"]
license = "MIT"
edition = "2021"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_with = "^2.0"
serde_json = "^1.0"
url = "^2.2"
uuid = { version = "^1.0", features = ["serde"] }
regex = "1.7.3"
[dependencies.reqwest]
version = "^0.11"
features = ["json", "multipart"]
