[package]
name = "clerk-rs"
version = "0.1.2"
authors = ["DarrenBaldwin07"]
description = "An unofficial Rust SDK for the Clerk API"
repository = "https://github.com/Cincinnati-Ventures/clerk-rs"
homepage = "https://cincinnati.ventures"
keywords = ["clerk", "auth", "sdk"]
license = "MIT"
edition = "2021"

[[example]]
name = "http"
path = "examples/http.rs"

[[example]]
name = "api"
path = "examples/api.rs"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_with = "^2.0"
serde_json = "^1.0"
url = "^2.2"
regex = "1.7.3"
[dependencies.reqwest]
version = "^0.11"
features = ["json", "multipart"]

[dev-dependencies]
clerk-rs = { path = "../clerk-rs" }
tokio = { version = "1.27.0", features = ["full"] }
